/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedNewsActivityRouteImport } from './routes/_authenticated/news-activity'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdmissionsRouteImport } from './routes/_authenticated/admissions'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedRoomsIndexRouteImport } from './routes/_authenticated/rooms/index'
import { Route as AuthenticatedStudentsStudentIdRouteImport } from './routes/_authenticated/students/$studentId'
import { Route as AuthenticatedRoomsRoomIdRouteImport } from './routes/_authenticated/rooms/$roomId'
import { Route as AuthenticatedConnectionsNewslettersRouteImport } from './routes/_authenticated/connections/newsletters'
import { Route as AuthenticatedConnectionsMessagesRouteImport } from './routes/_authenticated/connections/messages'
import { Route as AuthenticatedRoomsRoomIdIndexRouteImport } from './routes/_authenticated/rooms/$roomId/index'
import { Route as AuthenticatedStudentsStudentIdProfileRouteImport } from './routes/_authenticated/students/$studentId/profile'
import { Route as AuthenticatedStudentsStudentIdParentsRouteImport } from './routes/_authenticated/students/$studentId/parents'
import { Route as AuthenticatedStudentsStudentIdActivityRouteImport } from './routes/_authenticated/students/$studentId/activity'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewsActivityRoute =
  AuthenticatedNewsActivityRouteImport.update({
    id: '/news-activity',
    path: '/news-activity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdmissionsRoute = AuthenticatedAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoomsIndexRoute = AuthenticatedRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsStudentIdRoute =
  AuthenticatedStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoomsRoomIdRoute =
  AuthenticatedRoomsRoomIdRouteImport.update({
    id: '/rooms/$roomId',
    path: '/rooms/$roomId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConnectionsNewslettersRoute =
  AuthenticatedConnectionsNewslettersRouteImport.update({
    id: '/connections/newsletters',
    path: '/connections/newsletters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConnectionsMessagesRoute =
  AuthenticatedConnectionsMessagesRouteImport.update({
    id: '/connections/messages',
    path: '/connections/messages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoomsRoomIdIndexRoute =
  AuthenticatedRoomsRoomIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRoomsRoomIdRoute,
  } as any)
const AuthenticatedStudentsStudentIdProfileRoute =
  AuthenticatedStudentsStudentIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedStudentsStudentIdRoute,
  } as any)
const AuthenticatedStudentsStudentIdParentsRoute =
  AuthenticatedStudentsStudentIdParentsRouteImport.update({
    id: '/parents',
    path: '/parents',
    getParentRoute: () => AuthenticatedStudentsStudentIdRoute,
  } as any)
const AuthenticatedStudentsStudentIdActivityRoute =
  AuthenticatedStudentsStudentIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedStudentsStudentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/news-activity': typeof AuthenticatedNewsActivityRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/connections/messages': typeof AuthenticatedConnectionsMessagesRoute
  '/connections/newsletters': typeof AuthenticatedConnectionsNewslettersRoute
  '/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRouteWithChildren
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRouteWithChildren
  '/rooms': typeof AuthenticatedRoomsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/students/$studentId/activity': typeof AuthenticatedStudentsStudentIdActivityRoute
  '/students/$studentId/parents': typeof AuthenticatedStudentsStudentIdParentsRoute
  '/students/$studentId/profile': typeof AuthenticatedStudentsStudentIdProfileRoute
  '/rooms/$roomId/': typeof AuthenticatedRoomsRoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/admissions': typeof AuthenticatedAdmissionsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/news-activity': typeof AuthenticatedNewsActivityRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/connections/messages': typeof AuthenticatedConnectionsMessagesRoute
  '/connections/newsletters': typeof AuthenticatedConnectionsNewslettersRoute
  '/students/$studentId': typeof AuthenticatedStudentsStudentIdRouteWithChildren
  '/rooms': typeof AuthenticatedRoomsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/students/$studentId/activity': typeof AuthenticatedStudentsStudentIdActivityRoute
  '/students/$studentId/parents': typeof AuthenticatedStudentsStudentIdParentsRoute
  '/students/$studentId/profile': typeof AuthenticatedStudentsStudentIdProfileRoute
  '/rooms/$roomId': typeof AuthenticatedRoomsRoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_authenticated/admissions': typeof AuthenticatedAdmissionsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/news-activity': typeof AuthenticatedNewsActivityRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/connections/messages': typeof AuthenticatedConnectionsMessagesRoute
  '/_authenticated/connections/newsletters': typeof AuthenticatedConnectionsNewslettersRoute
  '/_authenticated/rooms/$roomId': typeof AuthenticatedRoomsRoomIdRouteWithChildren
  '/_authenticated/students/$studentId': typeof AuthenticatedStudentsStudentIdRouteWithChildren
  '/_authenticated/rooms/': typeof AuthenticatedRoomsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/students/$studentId/activity': typeof AuthenticatedStudentsStudentIdActivityRoute
  '/_authenticated/students/$studentId/parents': typeof AuthenticatedStudentsStudentIdParentsRoute
  '/_authenticated/students/$studentId/profile': typeof AuthenticatedStudentsStudentIdProfileRoute
  '/_authenticated/rooms/$roomId/': typeof AuthenticatedRoomsRoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admissions'
    | '/analytics'
    | '/billing'
    | '/calendar'
    | '/dashboard'
    | '/insights'
    | '/news-activity'
    | '/reports'
    | '/staff'
    | '/connections/messages'
    | '/connections/newsletters'
    | '/rooms/$roomId'
    | '/students/$studentId'
    | '/rooms'
    | '/students'
    | '/students/$studentId/activity'
    | '/students/$studentId/parents'
    | '/students/$studentId/profile'
    | '/rooms/$roomId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admissions'
    | '/analytics'
    | '/billing'
    | '/calendar'
    | '/dashboard'
    | '/insights'
    | '/news-activity'
    | '/reports'
    | '/staff'
    | '/connections/messages'
    | '/connections/newsletters'
    | '/students/$studentId'
    | '/rooms'
    | '/students'
    | '/students/$studentId/activity'
    | '/students/$studentId/parents'
    | '/students/$studentId/profile'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/login'
    | '/_authenticated/admissions'
    | '/_authenticated/analytics'
    | '/_authenticated/billing'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/insights'
    | '/_authenticated/news-activity'
    | '/_authenticated/reports'
    | '/_authenticated/staff'
    | '/_authenticated/connections/messages'
    | '/_authenticated/connections/newsletters'
    | '/_authenticated/rooms/$roomId'
    | '/_authenticated/students/$studentId'
    | '/_authenticated/rooms/'
    | '/_authenticated/students/'
    | '/_authenticated/students/$studentId/activity'
    | '/_authenticated/students/$studentId/parents'
    | '/_authenticated/students/$studentId/profile'
    | '/_authenticated/rooms/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/news-activity': {
      id: '/_authenticated/news-activity'
      path: '/news-activity'
      fullPath: '/news-activity'
      preLoaderRoute: typeof AuthenticatedNewsActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admissions': {
      id: '/_authenticated/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AuthenticatedAdmissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms/': {
      id: '/_authenticated/rooms/'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthenticatedRoomsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/$studentId': {
      id: '/_authenticated/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms/$roomId': {
      id: '/_authenticated/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connections/newsletters': {
      id: '/_authenticated/connections/newsletters'
      path: '/connections/newsletters'
      fullPath: '/connections/newsletters'
      preLoaderRoute: typeof AuthenticatedConnectionsNewslettersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connections/messages': {
      id: '/_authenticated/connections/messages'
      path: '/connections/messages'
      fullPath: '/connections/messages'
      preLoaderRoute: typeof AuthenticatedConnectionsMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rooms/$roomId/': {
      id: '/_authenticated/rooms/$roomId/'
      path: '/'
      fullPath: '/rooms/$roomId/'
      preLoaderRoute: typeof AuthenticatedRoomsRoomIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoomsRoomIdRoute
    }
    '/_authenticated/students/$studentId/profile': {
      id: '/_authenticated/students/$studentId/profile'
      path: '/profile'
      fullPath: '/students/$studentId/profile'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdProfileRouteImport
      parentRoute: typeof AuthenticatedStudentsStudentIdRoute
    }
    '/_authenticated/students/$studentId/parents': {
      id: '/_authenticated/students/$studentId/parents'
      path: '/parents'
      fullPath: '/students/$studentId/parents'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdParentsRouteImport
      parentRoute: typeof AuthenticatedStudentsStudentIdRoute
    }
    '/_authenticated/students/$studentId/activity': {
      id: '/_authenticated/students/$studentId/activity'
      path: '/activity'
      fullPath: '/students/$studentId/activity'
      preLoaderRoute: typeof AuthenticatedStudentsStudentIdActivityRouteImport
      parentRoute: typeof AuthenticatedStudentsStudentIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRoomsRoomIdRouteChildren {
  AuthenticatedRoomsRoomIdIndexRoute: typeof AuthenticatedRoomsRoomIdIndexRoute
}

const AuthenticatedRoomsRoomIdRouteChildren: AuthenticatedRoomsRoomIdRouteChildren =
  {
    AuthenticatedRoomsRoomIdIndexRoute: AuthenticatedRoomsRoomIdIndexRoute,
  }

const AuthenticatedRoomsRoomIdRouteWithChildren =
  AuthenticatedRoomsRoomIdRoute._addFileChildren(
    AuthenticatedRoomsRoomIdRouteChildren,
  )

interface AuthenticatedStudentsStudentIdRouteChildren {
  AuthenticatedStudentsStudentIdActivityRoute: typeof AuthenticatedStudentsStudentIdActivityRoute
  AuthenticatedStudentsStudentIdParentsRoute: typeof AuthenticatedStudentsStudentIdParentsRoute
  AuthenticatedStudentsStudentIdProfileRoute: typeof AuthenticatedStudentsStudentIdProfileRoute
}

const AuthenticatedStudentsStudentIdRouteChildren: AuthenticatedStudentsStudentIdRouteChildren =
  {
    AuthenticatedStudentsStudentIdActivityRoute:
      AuthenticatedStudentsStudentIdActivityRoute,
    AuthenticatedStudentsStudentIdParentsRoute:
      AuthenticatedStudentsStudentIdParentsRoute,
    AuthenticatedStudentsStudentIdProfileRoute:
      AuthenticatedStudentsStudentIdProfileRoute,
  }

const AuthenticatedStudentsStudentIdRouteWithChildren =
  AuthenticatedStudentsStudentIdRoute._addFileChildren(
    AuthenticatedStudentsStudentIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdmissionsRoute: typeof AuthenticatedAdmissionsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedNewsActivityRoute: typeof AuthenticatedNewsActivityRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedConnectionsMessagesRoute: typeof AuthenticatedConnectionsMessagesRoute
  AuthenticatedConnectionsNewslettersRoute: typeof AuthenticatedConnectionsNewslettersRoute
  AuthenticatedRoomsRoomIdRoute: typeof AuthenticatedRoomsRoomIdRouteWithChildren
  AuthenticatedStudentsStudentIdRoute: typeof AuthenticatedStudentsStudentIdRouteWithChildren
  AuthenticatedRoomsIndexRoute: typeof AuthenticatedRoomsIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdmissionsRoute: AuthenticatedAdmissionsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedNewsActivityRoute: AuthenticatedNewsActivityRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedConnectionsMessagesRoute: AuthenticatedConnectionsMessagesRoute,
  AuthenticatedConnectionsNewslettersRoute:
    AuthenticatedConnectionsNewslettersRoute,
  AuthenticatedRoomsRoomIdRoute: AuthenticatedRoomsRoomIdRouteWithChildren,
  AuthenticatedStudentsStudentIdRoute:
    AuthenticatedStudentsStudentIdRouteWithChildren,
  AuthenticatedRoomsIndexRoute: AuthenticatedRoomsIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
